cores: 20
thin: 2
iter: 10000 
warmup: 2000
init_r: 1
adapt_delta: 0.75
re_b: !expr c(3, 4, 5, 6, 7, 8)
quad_Xc: 7
penalty_family: t
penalty_term: !expr c(0, 0)
all_params: yes
pos_a: !expr c(1, 7, 11)
neg_a: !expr c(8, 9, 10, 19)
clean_state: yes
hiv_missing: 1
