cores: 10
thin: 40
chains: 1
iter: 6000 
warmup: 2000
init_r: 1
adapt_delta: 0.75
penalty_family: t
penalty-term: 0
all_params: yes
clean_state: yes
extra_x: !expr c( "clin_headache", "clin_psychosis")
use_rstan_compiler: yes
