---
bibliography: includes/references.bib
---

# Introduction

Tuberculous meningitis (TBM) is the most lethal form of *Mycobacterium tuberculosis* (*Mtb*) infection. Early diagnosis is critical to initiate appropriate therapy, especially for low-middle-income countries, where access to the diagnostic tests is limited. Nevertheless, diagnosing TBM is notoriously challenging as no gold standard exists. A confirmatory diagnosis of TBM requires identification *Mtb* of in cerebrospinal fluid (CSF), but conventional tests – Ziehl-Neelsen smear (ZN-Smear) microscopy, GeneXpert MTB/RIF (Xpert), and culture by Mycobacteria Growth Indicator Tube (MGIT) – lack sensitivity due to the challenge of Mtb identification in paucibacillary CSF [@nhu2013; @chen2020].

A diagnosis of TBM is often guided by a combination of clinical, biochemical, and imaging features. TBM is suggested by a long duration of symptoms at presentation and abnormal CSF biomarker values. A number of diagnostic algorithms have been created that utilise this information  [@thwaites2002; @moreira2008; @marais2010; @le2020]. However, many of these have not been widely validated, especially for those individuals for whom the true disease status could not be verified.

In 2010, a uniform case definition (UCD) was developed based on expert opinion [5]. This illustrated the diagnostic challenges presented by TBM and was intended to facilitate comparison of research data, rather than for use in clinical practice. The UCD distinguishes between four diagnostic levels: *definite*, *probable*, *possible*, and *not* TBM. Individuals with microbiological or molecular confirmation of *Mtb* within the CSF are allocated to *definite* TBM. The remaining cases are defined as *probable* or *possible,* encompassing an expert-generated grading system where higher scores designate an increased probability of a diagnosis of TBM. It is expected that true TBM cases are represented by all *definite* cases, most *probable* cases, and some *possible* cases. Since TBM is almost always fatal if not treated with anti-tuberculosis drugs, and delayed treatment is strongly associated with death or severe neurological sequelae in survivors, physicians usually err on the side of TBM treatment for those with compatible symptoms despite on-going diagnostic uncertainty.

In social science and psychology a technique named *Latent class analysis (LCA)* or *Latent class model (LCM)* has been employed that has the ability to infer “hidden groups” (called latent classes) based on “observed indicators”. The individual allocation into each group can be improved by relating it to “additional features”. LCA was later adopted in diagnostic studies to answer a similar problem when there is no practical gold standard to determine the disease status, as in the case of pulmonary tuberculosis and TBM [@schumacher2016; @stout2018; @lahuerta-marin2018; @adams2019].

The rationale and formulation of our LCA is discussed in the clinical and statistical supplementary appendices. In our study, we defined two “hidden groups”, those infected with Mtb and those infected with another pathogen, and the “observed indicators” are the three confirmatory tests (ZN-Smear, MGIT, and Xpert). The “additional features”, herein referred as "diagnostic features" in our study, are the clinical, biochemical and imaging diagnostic features as used in the uniform case definition in combination with a few characteristics that are strongly indicative of not having TBM. The main purpose of our study is to use the confirmatory test results and the diagnostic features to estimate TBM status per individual and develop a calibrated scoring system that quantifies the risk of TBM based on the diagnostic features. Our model allowed us to re-evaluate the performance of each confirmatory test. To improve the clinical usability, we also developed a simplified scoring system requiring only clinical information and chest X-ray, without CSF analysis.
