# Methods

## Participants

We used data from an observational study of brain infection conducted on the neuro-infection ward of the Hospital for Tropical Diseases (HTD), Ho Chi Minh City, Vietnam. HTD is a 550-bed centre providing secondary and tertiary treatment for a wide range of tropical infections from all of southern Vietnam [@thwaites2002]. The study received ethical approvals from HTD and the Oxford Tropical Research Ethics Committee [@donovan2020]. Participants were enrolled between 29th August 2017 and 22nd January 2021. Inclusion criteria were a minimum age of 16 years, having suspected brain infection of any cause, and undergoing lumbar puncture at baseline as a routine diagnostic procedure. Patients were ineligible for enrolment if performing a lumbar puncture was contraindicated, or if informed consent to join the study was not given (by the patient, or by a relative if the patient lacked capacity to consent). For this study, we also excluded patients with contaminated mycobacterial culture results and without a subsequent culture in the first week since admission.

## Data collection and pre-processing

At enrolment, demographic information and medical history were collected. Patients with unknown HIV status were tested for HIV if they presented with a condition suggestive of immune deficiency (e.g. tuberculosis, or cryptococcal meningitis) or had been involved in activities that increased HIV risk (e.g. injecting drug use). Patients underwent clinical examination and chest X-Ray - but no brain imaging session. Laboratory investigations included blood, sputum ZN staining and lumbar puncture. Routine CSF analysis included  white blood cells and cellular differential, protein, glucose (with paired blood glucose), and lactate. Ideally at least 6mls CSF was used for mycobacterial testing by Smear, MGIT, and GeneXpert MTB/RIF (Xpert) or Xpert MTB/RIF Ultra (XpertUltra). Since Xpert and XpertUltra were found diagnostically comparable [@donovan2020], they were combined and denoted as Xpert. If CSF was repeatedly sampled (performed based on clinical need), we only used the first sample with at least 3mls of CSF collected, and not later than the first week since admission. Methods of CSF processing have been described in details [@donovan2020]. Briefly: CSF samples were centrifuged at 3000g for 15 minutes, and most of the CSF supernatant was removed. The CSF deposit was resuspended in 500µL of remaining supernatant, with this resuspended pellet then used for ZN smear (100µL), MGIT (200µL), and Xpert (200 µL). Laboratory tests for differential diagnoses routinely used were Gram stain for other bacterial meningitis, eosinophilic cell count in the CSF as an indicator for eosinophilic meningitis, and Indian-ink stain or CSF lateral flow antigen providing confirmatory evidence for Cryptococcal meningitis.

All patients with confirmed or suspected TBM received 4-drug anti-TB chemotherapy regimens according to national and local treatment guidelines. At the time of discharge or death, all patients received a final diagnosis (hospital diagnosis). If at least one of Smear, Xpert, or MGIT from CSF was positive at any time during the follow-up, the patient was considered to have confirmed TBM. the patient was considered to have suspected TBM if confirmatory microbiological and molecular tests were negative, but TBM was clinically suspected and treated. Patients that recovered without anti-TB chemotherapy, or had an alternative diagnosis confirmed microbiologically, were assigned another diagnosis (i.e. not TBM).

The inclusion of relevant risk factors for TBM based on prior knowledge [@marais2010]. Prior knowledge of the association of these factors with TBM status and bacterial burden is shown in Supplementary Table \@ref(tab:predictor-tab). We added three variables indicating alternative diagnoses: (1) CSF eosinophil count - a strong biomarker for eosinophilic meningitis, a relatively common condition in Vietnam, usually caused by *Angiostrongylus cantonensis*; (2) CSF lateral flow antigen/Indian Ink tests for cryptococcal meningitis; and (3) CSF Gram stain for non-acid-fast bacterial meningitis. Also added was CSF red cell count whose high numbers being a marker of traumatic lumbar puncture requiring corrections to white cell counts and biochemical features [@greenberg2008; @nigrovic2011; @mehl1986]. Compared to the uniform case definition, we changed past TB contact to “noticeable contact with TB patients within the past year” so all missing answers could be interpreted as "No".

## Statistical analysis {#stats-analysis}

The basic design of our model is shown in Figure \@ref(fig:skeleton-model) and explained in detail in Supplementary Section \@ref(appendix-model-spec). In the middle is TBM status, which is unknown for many individuals. The fundamental component in the latent class model (LCM) links TBM status to the test results from Xpert, MGIT and Smear; they are called the manifest variables. In LCM, he important assumption is that these test results are independent given TBM status and the additional variables. To achieve this, we added bacillary burden as variable for individuals with TBM. Since we didn’t measure this value, it was modelled as a combination of an unmeasured random effect [@qu1996] and a set of known covariates. We allowed bacterial burden to depend on HIV status and the CSF values of glucose, lymphocyte count, total white blood-cell (WBC) count, protein, and lactate. The second component is a logistic regression prevalence model that relates TBM status to the set of risk factors that we described in Section \@ref(data-collection-and-pre-processing).
If TBM status were known for every individual, the prevalence model would be all we need to come up with a diagnostic score. We need the LCM to provide additional information on unknown TBM status. The LCM provides individual estimates of the probability to have TBM based on the test results and the additional characteristics. These individual probabilities provide the data to compute sensitivity and specificity of each of the three test procedures and to relate TBM status to the diagnostic variables in the prevalence model. 

An important issue in latent class models is identifiability [@berzofsky2012]. We chose a Bayesian approach, which has the advantage that we can use prior knowledge on test sensitivity and specificity via more informative priors. We used results from earlier studies [@thwaites2004; @nhu2013; @heemskerk2018]. Weakly informative prior distributions were used for all model coefficients. Posterior estimations were obtained via Hamiltonian Markov Chain Monte Carlo using probabilistic package Stan version 2.27 [@stan-doc]. Convergence was evaluated by the Brooks-Gelman-Rubin statistic [@stan-doc]. Results are presented as means and 50%/95% credible intervals. Further details are given in Supplementary Section \@ref(appendix-prior-choices). 

Using estimates from the model, we additionally *(1)* fitted a simplified logistic regression prevalence model (simplified model) against the allocated TBM status that excluded laboratory information based on the estimates of which we provided a quick screening score table and *(2)* calculated an updated probability to have TBM after retrieving results of some or all confirmatory assays, relative to the pre-test TBM probability outputted from our prevalence model. Because any positive test means definite TBM and MGIT is usually the most delayed test, we limited to five scenarios where different sets of confirmatory test were available and negative at diagnosis: _(a)_ only Smear, _(b)_ only Xpert, _(c)_ Smear and MGIT, _(d)_ Smear and Xpert, and _(e)_ all three tests. 

By protocol, the three TBM tests were not performed if patients were not suspected of TBM. As these tests are known to have high specificity [@nhu2013, @heemskerk2018], we assumed that they were all negative. These assumptions will be tested by sensitivity analyses (Supplementary Section \@ref(appendix-senanalysis)). Missing values were handled based on their expected missingness mechanism (Supplementary Section \@ref(appendix-data)).

We considered five different models with increasing complexity, somewhat similar to an earlier study on childhood pulmonary tuberculosis [@schumacher2016]. We selected the best model out of five using the expected log point-wise predictive density (elpd) [@vehtari2016]. We evaluated diagnostic model performance in several ways: visualised calibration curves [@VanCalster2019], receiver operating characteristic (ROC) curves and computed area under the ROC curve (AUC) for all three confirmatory tests (LCM). We additionally used the hospital diagnosis made by physicians as a pseudo-gold standard to validate our prevalence model. The optimal cut point for TBM classification was chosen using Youden’s Index. For model selection and all evaluations, we used 20-fold cross validations with 5 repetitions for the LCA model and 20 repetitions for the simplified model.

All analyses were performed on statistical package R, version 4.1.2 [@rcoreteam]. All code were published on project's github repo [@tbmrepo].

```{r skeleton-model, fig.show='hold', out.width="100%", fig.align="center", fig.cap="Basic model design: TBM risk factors predict individual's TBM status. Unknown TBM status is linked with test results. The probability of a positive test depends on bacillary burden. Test positive probabilities are for demonstration only and do not correspond to the real one.", fig.id='skeleton-model'}

fig_svg <- cowplot::ggdraw() + 
  cowplot::draw_image(magick::image_read_svg("includes/classicLCA.svg", width=212*5))
plot(fig_svg)
```

<!--Since latent class analysis models unobserved characteristics, results may be strongly dependent on our assumptions. Therefore, we conducted sensitivity analyses where some assumptions were lifted or changed. We first increased the standard deviation of our prior for specificities of all confirmatory tests so that every value in the range of 90%-100% were accepted. We also changed the prior distributions of the parameters in the prevalence and bacillary burden models from *normal* to a more skeptical one *Student's t* with 4 degrees of freedom; means and scales, however, were kept as-is. Their *elpd*s were compared. Thirdly, as recent studies suggested a sup-optimal specificity of Xpert test on CSF samples [@nhu2013; @chen2020], we considered a Missing-At-Random scenario, where observation chance of confirmation tests depend on the unknown TBM status and locally independent to the value of confirmation tests. Observation status was then included in the model as a separated manifest variables. We visualised the estimates of this model with the best performing one in our main analysis.

Furthermore, to explore hidden effects, we added quadratic terms for all five CSF bio-markers and RGCS to the prevalence model; CSF volume was additionally included to capture its potential impact on test sensitivity. *Laplace* priors were utilised instead of *Normal* for all linear covariates. Posteriors and performance metrics of this model were reported.-->

<!-- All data preparation, cleaning, and processing were performed on statistical package R, version 4.1.1 [@rcoreteam]. Posterior distributions were obtained via Hamiltonian Markov Chain Monte Carlo with 8000 effective iterations in each of 4 chains, using RStan [@stan-doc] package, version 2.27 [@stan]. <!--. Plotting was done using package bayesplot [@bayesplot], classifierplots [@classifierplots], and ggvenn [@ggvenn]. Post-hoc linear mixed-effect model was fitted by package lme4 [@lme4]. -->

