# Results

## Clinical characteristics

Of the `r nrow(data_dirty)` participants, `r nrow(data_19EI)` were included in the analysis (Figure \@ref(fig:patient-flow)). All participants had at least one symptom suggestive of a brain infection (headache, fever, neck stiffness, vomiting, convulsion).  Characteristics of included individuals are summarised in Table \@ref(tab:test-bl-tbl), stratified by overall and specific confirmatory test results. The median age of included individuals was `r quantile(data_19EI$age, .5, na.rm=TRUE) |> round(1)` years. HIV co-infection status was assessed for `r nrow(data_19EI) - na(data_19EI$hiv_stat)`/`r nrow(data_19EI)` (`r round((nrow(data_19EI) - na(data_19EI$hiv_stat))/nrow(data_19EI)*100, 0)`%) individuals, amongst whom `r sum(data_19EI$hiv_stat, na.rm=TRUE)` (`r round(sum(data_19EI$hiv_stat, na.rm=TRUE)/sum(!is.na(data_19EI$hiv_stat))*100, 0)`%) were positive. For each of the confirmatory tests, both HIV prevalence and duration from symptom onset to hospitalisation was higher in the test positive group than in the negative and missing groups. There were `r var[5]-var[6]` participants with valid TBM confirmatory test results, of whom `r var[7]` were microbiologically confirmed TBM (Figure \@ref(fig:venn-test)), while `r var[11]` were later confirmed with another disease. Amongst the `r var[4]` patients that were not tested microbiologically for TBM, `r var[9]` were confirmed with another pathogen. For `r var[8]+var[10]` patients, from both the tested and the untested group, no confirmed diagnosis could be made.

## Model estimates

Estimated coefficients for TBM diagnostic features in the prevalence model are shown in Figure \@ref(fig:coef-est). HIV infection, miliary TB, and longer symptom duration were associated with higher risk of TBM. Of the laboratory variables, there was a strong increase of TBM risk with higher lymphocyte count and weaker increase with lower paired blood glucose, lower CSF glucose, higher CSF protein, and higher lactate. The relationship between CSF WBC count and TBM risk was nonlinear, peaking at 238 WBC per mm^3^ of CSF. HIV infection and higher CSF protein were associated with higher mycobacillary burden, while higher Glasgow coma score (GCS), CSF glucose, WBC and lymphocyte count all associated with lower mycobacillary burden.

Estimates of sensitivity and specificity of ZN-Smear, MGIT, and Xpert in diagnosing TBM are reported in Table \@ref(tab:mv-posterior). Specificity of each is > 99%. ZN-Smear was the most sensitive test with sensitivity `r sen('z_Smear', hiv=FALSE, str = '{median} ({ci})')` for people without HIV and `r sen('z_Smear', hiv=TRUE, str = '{median} ({ci})')` for those with HIV. Xpert was the least sensitive, especially in the former group, at `r sen('z_Xpert', hiv=FALSE, str = '{median} ({ci})')`. The sensitivity of Xpert was much higher in the group with HIV, at `r sen('z_Xpert', hiv=TRUE, str = '{median} ({ci})')` and comparable to MGIT sensitivity.

## Model validation 

Our selected indicator model showed good discrimination with AUCs of `r (pROC::auc(response = data_19EI$csf_smear, predictor = m3$p$p_Smear$mean)*100) |> formatC(format='f', digits=1)`% for ZN Smear, `r (pROC::auc(response = data_19EI$csf_mgit, predictor = m3$p$p_Mgit$mean)*100) |> formatC(format='f', digits=1)`% for MGIT, and  `r (pROC::auc(response = data_19EI$csf_xpert, predictor = m3$p$p_Xpert$mean)*100) |> formatC(format='f', digits=1)`% for Xpert (Figure \@ref(fig:model-metrics)). The model was also well calibrated: estimated probabilities and smoothed frequency of positive tests showed good overall agreement [@VanCalster2019]. When comparing TBM risk prediction against the final hospital diagnosis, the AUC was  `r (pROC::auc(response = !data_19EI$other_dis_dx, predictor = m3$p$theta$mean)*100) |> formatC(format='f', digits=1)`% and the calibration plot showed a good correspondence between the two.

## Updated TBM risk if some or all confirmatory tests are negative
 
The changes in TBM risk relative to the pre-test values are shown in Table \@ref(tab:tbl-post-test). A negative ZN-Smear alone halves the probability of TBM regardless of HIV status. A negative ZN-Smear and Xpert was associated with a `r post_test$get_est("smear_xpert", inv = TRUE, hiv=TRUE, str = '{median}')`-fold reduction in TBM risk for participants with HIV and a `r post_test$get_est("all", hiv=FALSE, inv = TRUE, str = '{median}')`-fold reduction for those without HIV. With all tests negative, the TBM probability reduced by `r post_test$get_est("all", inv = TRUE, str = '{median}')` and `r post_test$get_est("all", hiv=TRUE, inv = TRUE, str = '{median}')`, respectively for the two groups above. 

## Simplified model

Most included diagnostic features in the simplified prevalence model associated with TBM status (Figure \@ref(fig:simplified-model-plot)). The association was not clear with focal neurological deficit. Three of the four additional symptoms suggested a TBM diagnosis, only psychosis made another diagnosis more likely.

Our simplified model had good AUC. The cutpoint maximising Youden's index is at a probability to have TBM of 30.7%, where our model was 79.0% sensitive and 75.0% specific. We used this cutpoint to derive a screening score table by selecting rounded parameter values within the 50% credible intervals of every coefficient. All the scores and the threshold were subsequently multiplied by a factor of 2 to make the calculation easier  (Table \@ref(tab:score-table)).