<!-- method -->
```{r skeleton-model, fig.show='hold', out.width="100%", fig.align="center", fig.cap="Basic model design: TBM risk factors predict individual's TBM status. Unknown TBM status is linked with test results. The probability of a positive test depends on bacillary burden. Test positive probabilities are for demonstration only and do not correspond to the real one.", fig.id='skeleton-model'}

fig_svg <- cowplot::ggdraw() + 
  cowplot::draw_image(magick::image_read_svg("includes/classicLCA.svg", width=212*5))
plot(fig_svg)
```

<!-- Result -->

```{diagrammer patient-flow, fig.show="hold", out.width="100%", out.height="10cm",  fig.align="center", fig.cap="Recruited patient profile", fig.id="patient-flow"}
#check final number
digraph patientflow {
  # compound = true;
  graph[fontname="CMU Serif", splines=line];
  node[fontname = "CMU Serif", shape="rectangle"];
  # edge[splines=line]
  
  Total [label = "@@1 enrolled and have CSF samples collected" ]
  n1[shape="circle",width=0,height=0, label=""];
  n2[shape="circle",width=0,height=0, label=""];
  n3[shape="circle",width=0,height=0, label=""];
  n4[shape="circle",width=0,height=0, label=""];
  n5[shape="circle",width=0,height=0, label=""];
//   n6[shape="circle",width=0,height=0, label=""];

  subgraph exclude1{
    WrongName [label ="@@2 excluded due to mis-matched names"]
    LowVolume [label = "@@3 excluded due to low CSF volume collected within 7 days"]
    Tested [label = "@@5 tested for TBM"]
  }
  

    Contaminated [label = "@@6 excluded due to contaminated culture"]
  {rank=same; n1; WrongName}
  {rank=same; n2; LowVolume}
  {rank=same; n4; Contaminated}
  {rank=same; n3; n5}
  NotTested [label = "@@4 not tested for TBM"]
  # {rank=same; WrongName; LowVolume}
  {rank=same; Tested; NotTested}
  
  TBM [label = "@@7 confirmed TBM\l\n@@12 suspected TBM\l\n@@11 confirmed other cause\l\n@@8 unconfirmed cause\l"]
  NotTBM [label = "@@9 confirmed other disease\l\n@@10 unconfirmed cause\l"]
  {rank=same; TBM; NotTBM};
  
  Total:s -> n1:n[dir=none];
  WrongName -> n1[dir=back];
  n1:s -> n2:n[dir=none];
  LowVolume -> n2[dir=back];
  n2:s -> n3:n[dir=none];
  n3 -> n5[dir=none];
  n5:s -> NotTested:n
  n5:w -> NotTested:e[style=invis];
  n3:s -> Tested:n
  NotTested:s -> NotTBM:n
  NotTested:s -> NotTBM:n
  Tested:s -> n4:n[dir=none]; 
  Contaminated -> n4[dir=back];
  n3:w -> Contaminated:n[style=invis];
  n4:s -> TBM:w[style=invis];
  n4:s -> TBM:n;
}
[1]: var[1]
[2]: var[2]
[3]: var[3]
[4]: var[4]
[5]: var[5]
[6]: var[6]
[7]: var[7]
[8]: var[8]
[9]: var[9]
[10]: var[10]
[11]: var[11]
[12]: var[12]
```

```{r venn-test, out.width='50%', fig.align='center', fig.asp=1, fig.width=6, fig.cap = 'Venn diagram for ZN Smear, MGIT, and Xpert'}

# data_19EI |>
#   mutate(across(c(csf_smear, csf_mgit, csf_xpert), as.logical)) |>
#   ggplot() +
#   ggvenn::geom_venn(aes(A = csf_smear, B = csf_mgit, C = csf_xpert), 
#                     fill_color = c('#E5707E', '#E6B566', '#A3DDCB'),
#                     stroke_color = c('#E5707E', '#E6B566', '#A3DDCB'),
#                     set_names = c('ZN Smear', 'MGIT', 'Xpert'),
#                     text_size = 3, set_name_size = 4) +
#   theme_void()

eulfit = eulerr::euler(c("a" = 44, "b" = 17, "c" = 1, "a&b"=19, "a&c"=14, "b&c"=8, "a&b&c"=64))
plot(eulfit, 
     fills = c('#E5707E', '#E6B566', '#A3DDCB'), 
     edges=c('#E5707E', '#E6B566', '#A3DDCB'), 
     labels = c(a='ZN-Smear', b='MGIT', c='Xpert'), 
     quantities=list(
       labels =
         c('44 (31.9%)', '12 (8.7%)', '0 (0.0%)', 
           '8 (5.8%)', '9 (6.5%)', '1 (0.7%)', '64 (46.4%)'), 
       fontsize = 10), 
     adjust_labels=TRUE)
```

```{r coef-est, out.width="90%", fig.dim=c(8, 10), fig.align="center", fig.cap="A: Estimates of TBM odd ratios in prevalence model for different covariates, excluding WBC count; B: Estimates of TBM odd ratio for each value of CSF WBC count; C: Estimates of factors impacting individual's bacillary burden, given they have TBM. In A and C: dot, thick lines, and thin lines are posterior expected values, 50\\% and 95\\% credible intervals. In B: the blue line is expected odds ratio, the inner ribbon and outer ribbon are 50\\% and 95\\% credible intervals.", fig.id="coef-est", warning=FALSE, message=FALSE}

library(patchwork)

# rotate xlab 45deg
# log10(eos) > 0 wrong -> eos > 0
# odd ratio
# C: standardised bacillary burden #explain in text
y_labs = m3$a_plot$scales$get_scales('y')$labels
y_labs[3] = "*log<sub>10</sub>* (CSF RBC)"
y_labs[4] = "*log<sub>10</sub>* (CSF Eosinophil)" 
y_labs[5] = 'CSF Eosinophil > 0'
y_labs[6] = "*log<sub>10</sub>* (CSF Lymphocyte)"

y_labs2 = m3$b_plot$scales$get_scales('y')$labels
y_labs2[1] = "*log<sub>10</sub>* (CSF WBC)"  
y_labs2[2] = "*log<sub>10</sub>* (CSF Lymphocyte)"

ab_plot = ((m3$a_plot |> td.misc::change_ylabs(rev(y_labs), top_down = TRUE)) + ggtitle("Prevalence model") + 
             scale_x_continuous(
               name="TBM odd ratio",
               breaks = m3$a_plot$scales$get_scales('x')$breaks,
               labels = m3$a_plot$scales$get_scales('x')$labels) + 
             theme(axis.text.y = ggtext::element_markdown())) / 
  (m3$wbc_plot + theme(axis.title.y=element_text(size=8, face='bold',vjust=-45, color=grey(.3))) +
     scale_y_continuous(
    name = 'TBM odd ratio',
    breaks = log(10^c(-24,-20, -16,-12, -8,-4,-2, -1, 0)),
    labels = c('1e-24','1e-20','1e-16','1e-12','1e-8', '1e-4', 0.01, .1, 1)
  )) /
  ((m3$b_plot |> td.misc::change_ylabs(rev(y_labs2), top_down = TRUE)) + 
     ggtitle("Bacillary burden model") + 
     theme(axis.text.y = ggtext::element_markdown()) + 
     scale_x_continuous(name='Standardised bacillary burden')) /
  # grid::rasterGrob(restab_raster) + 
  patchwork::plot_layout(ncol=1, nrow=3, 
                         heights = c(6,2,2)) + 
  plot_annotation(tag_levels="A")

#ggtitle("CSF WBC count") + theme(title = element_text(face='bold',size=6), title.po

# plt = patchwork::wrap_plots(ab_plot, m3$plot.multggplotGrob(m3$rocs)) + plot_annotation(tag_levels="A")
# plot(plt)
ab_plot
```



```{r coef-est.old, fig.align='center', fig.asp=1.4, fig.cap='Posterior estimates (mean and 50%/95% credible intervals) of coefficients of risk factors for TBM (prevalence model) and variables that impact bacillary burden (latent class model)', message=FALSE, warning=FALSE, out.width='100%', include=FALSE, eval=FALSE}
(a_plot + ggtitle('TBM Risk factor')) /
  (b_plot + scale_x_continuous() + ggtitle('Bacillary burden predictors')) + 
  plot_layout(nrow=2, heights=c(7,2))&
  theme(text = element_text('serif', size = 9), plot.tag = element_text('serif', size = 9), axis.text.y = ggtext::element_markdown(family=NULL, face='bold'), legend.position = "none") 
```


```{r model-metrics, fig.align="center", fig.cap='Model performance. A: ROC and AUC against confirmatory test results; B: calibration against confimatory test results; C: ROC and AUC against hospital diagnosis; D: Calibration against hospital diagnosis. For calibration plots, “observed” probabilities are defined as values smoothed by a loess fit against observed binary events, in which the translucent ribbons represent the level of uncertainty of the smoothing. For ROC plots, AUC values are presented as \\emph{“average (min - max over 5 repetitions of cross-validation)”}; the grey lines are fitted curves from each 20-fold cross validation and coloured lines represents their average.' , fig.dim=c(9, 12), fig.show='hold', message=FALSE, warning=FALSE, out.width='80%', fig.id="model-metrics"}

roc_y <- do.call(gridExtra::arrangeGrob, m3$ROC$Y)
m3$calib$Y[[3]] = m3$calib$Y[[3]] + theme(axis.title.y = element_blank())
(wrap_elements(roc_y) / wrap_elements(m3$calib$Y)) /
  (wrap_elements(m3$ROC$C) + wrap_elements(m3$calib$C)) + 
  plot_layout(heights=c(2,2,3)) +
  plot_annotation(tag_levels = 'A')
```

```{r best-metrics.old, include=FALSE, eval=FALSE, fig.align='center', fig.cap='ROC curves (upper half) and calibration plots (lower half) against observed test results for the selected model. Results from each of the 5 CV repetitions are shown in grey and the average curves are in colour.', fig.dim=c(8,6), dpi=600, message=FALSE, warning=FALSE, out.width='90%'}
w = wrap_plots(m3_roc$Y, m3_calib$Y, ncol=1, heights=c(1,1))
plot(w)
```

```{r theta-metrics-prep, include=FALSE, eval=FALSE}
theta_rocs <- m3_roc$C + ggtitle('Hospital Diagnosis') + theme_bw()
theta_calib <- m3_calib$C
```

```{r theta-metrics, fig.align='center', fig.cap='ROC curves and calibration plots for prevalence model againts discharge diagnosis. Results from each of the 5 individual CV repetitions are shown in grey and the average curves are in colour.', fig.dim=c(10,5), dpi=600, message=FALSE, warning=FALSE, out.width='100%', include=FALSE, eval=FALSE}
theta_rocs+theta_calib
```

```{r simplified-model-plot, fig.align='center', fig.cap="A: Posterior estimates of coefficients of clinical TBM risk factors. Points, thick lines, and thin lines are posterior means, 50\\% and 95\\% credible intervals. B: Calibration plot of the simplified model, expected posterior probability of prevalence model. “Observed” probabilities are defined as values smoothed by a loess fit against observed binary events, in which the translucent ribbons represent the level of uncertainty of the smoothing. C: ROC plot and AUC of the simplified model, against hospital diagnosis. AUC values are presented as \\emph{“average (min - max over 20 repetitions of cross-validation)”}.", message=FALSE, warning=FALSE, out.width='100%', dpi=600, fig.dim=c(9, 8), fig.id = "simplified-model-plot"}
# tmp_svg <- cowplot::ggdraw() + 
#   cowplot::draw_image(magick::image_read_svg("includes/a_plog_s.svg", width=212*5, height=159*5))
# plot(tmp_svg)
a_plot_s <- s_plots$a_plot_s + 
  theme(
    #text = element_text('serif', size = 10), 
    #plot.tag = element_text('serif', size = 10), 
    axis.text.y = ggtext::element_markdown(family=NULL, face='bold'), legend.position = "none") 
metrics_s <- readRDS(file.path(data_dir, '..', 'export', 'metrics', 's_plot.RDS')) 

(a_plot_s + (metrics_s$calib/ (metrics_s$roc))) + plot_annotation(tag_levels = 'A')
```
